services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_qayim
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jeffxddowdowdow1234   # Match the password in your .env
      MYSQL_DATABASE: qayyim_db                   # Set this to the same value as in your .env (qayyim_db)
    ports:
      - "3307:3306"  # Port 3307 on host to 3306 in container
    volumes:
      - mysql_data2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_qayim
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root                           # Match the user in your .env (root or user)
      PMA_PASSWORD: Jeffxddowdowdow1234           # Password from your .env
    ports:
      - "8080:80"  # Access phpMyAdmin on localhost:8080
    depends_on:
      - mysql

volumes:
  mysql_data2:
